QT += widgets
CONFIG += c++17 warn_on
TARGET = compositor-arc
TEMPLATE = app
SOURCES += src/main.cpp src/document.cpp src/canvas.cpp src/window.cpp
HEADERS += src/document.h src/canvas.h src/window.h
SOURCES += src/painting.cpp
HEADERS += src/painting.h
SOURCES += src/operations.cpp
HEADERS += src/operations.h
SOURCES += src/selection.cpp ../Compositor/Rendering/WandPixels.c
HEADERS += src/selection.h
SOURCES += src/filters.cpp ../Compositor/Rendering/AdjustPixels.c ../Compositor/Rendering/LevelsPixels.c ../Compositor/Rendering/NoisePixels.c ../Compositor/Rendering/LensPixels.c ../Compositor/Rendering/ContentFill.c
HEADERS += src/filters.h
SOURCES += src/retouch.cpp ../Compositor/Rendering/HealPixels.c
HEADERS += src/retouch.h

SOURCES += src/styles.cpp
HEADERS += src/styles.h
SOURCES += src/style_dialogs.cpp
SOURCES += src/blending.cpp
HEADERS += src/blending.h
SOURCES += src/hierarchy.cpp
HEADERS += src/hierarchy.h
HEADERS += src/layer_tree.h
SOURCES += src/clipping.cpp
HEADERS += src/clipping.h
SOURCES += src/masks.cpp
HEADERS += src/masks.h
